# Generated by Django 5.2.12 on 2026-03-28 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_post_parent"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(fields=["updated_at"], name="forum_thread_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(fields=["created_at"], name="forum_thread_created_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["thread", "created_at"], name="forum_post_thread_created_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["author", "created_at"], name="forum_post_author_created_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_read", "created_at"], name="forum_notif_recipient_idx"),
        ),
        migrations.CreateModel(
            name="ModerationWarning",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("rep_penalty", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to="forum.post",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to="forum.thread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "created_at"], name="forum_warn_user_created_idx")],
            },
        ),
        migrations.CreateModel(
            name="ReputationGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_grants_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_grants",
                        to="forum.post",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_grants_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_grants",
                        to="forum.thread",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["recipient", "created_at"], name="forum_repgrant_recipient_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("actor", "thread"), name="forum_repgrant_actor_thread_unique"),
                    models.UniqueConstraint(fields=("actor", "post"), name="forum_repgrant_actor_post_unique"),
                ],
            },
        ),
    ]
