# Generated by Django 5.2.12 on 2026-03-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_reputation_and_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("soft_delete", "Soft Delete"),
                    ("hard_delete", "Hard Delete"),
                    ("restore", "Restore"),
                    ("warn_user", "Warn User"),
                    ("report_resolve", "Report Resolve"),
                    ("report_dismiss", "Report Dismiss"),
                    ("thread_flag", "Thread Flag"),
                ],
                max_length=20,
            ),
        ),
    ]
